### ISSUE TITLE
Inconsistency in UPGRADING.md

### ISSUE THREAD

**Issue by kennethgeerts** [RIPAGlobal/omniauth-entra-id#38]
In the [upgrade documentation](https://github.com/RIPAGlobal/omniauth-entra-id/blob/master/UPGRADING.md#callback-routes), "Callback routes" section the URL `https://example.com/v1/auth/entra/callback` mentions `entra` in stead of `entra_id`.

**Comment by washu** [comment]
you should make a pull request

**Comment by pond** [comment]
Fixed by #40 - thanks!
